import React from 'react';
import styles from '../styles/About.module.scss';
import Image from 'next/image';
import Head from 'next/head';

const About = () => {
  return (
    <>
    <Head>
      <title>Next About Page</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <div className='bg-info'>
        <h2 className={styles.about_text}>This is about file.</h2>
        {/* <img src='https://blog.rocketseat.com.br/content/images/2018/12/ssr-nextjs-reactjs.png'/> */}
        {/* <img src='/ssr-nextjs-reactjs.png' /> */}
        <Image src='/ssr-nextjs-reactjs.png' width={1300} height={800}/>
    </div>
    </>
  )
}

export default About